---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hackweek-nextjs
  name: hackweek-nextjs

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: hackweek-nextjs
